---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arbeidsforhold
  namespace: default
  labels:
    team: personbruker
spec:
  image: navikt/arbeidsforhold:1
  team: personbruker
  port: 8080
  ingresses:
    - https://arbeidsforhold.nais.adeo.no
  liveness:
    path: "/isAlive"
    initialDelay: 10
  readiness:
    path: "/isReady"
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: "3"
      memory: "768Mi"
    requests:
      memory: "512Mi"
