---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arbeidsforhold
  namespace: default
  labels:
    team: personbruker
spec:
  image: navikt/arbeidsforhold:7
  team: personbruker
  port: 80
  ingresses:
    - https://arbeidsforhold.nais.preprod.local/person/arbeidsforhold
    - https://www-q0.nav.no/person/arbeidsforhold
  liveness:
    path: /person/arbeidsforhold/isAlive
    initialDelay: 10
  readiness:
    path: /person/arbeidsforhold/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: "3"
      memory: "768Mi"
    requests:
      memory: "512Mi"
