# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build-react-app:
    docker:
      - image: circleci/node:11.7.0

    steps:
      - checkout
      - restore_cache:
          name: Modul - Restore cache
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Modul - Installer npm pakker
          command: |
            npm ci
      - save_cache:
          name: Modul - Save cache
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Modul - Bygg React app
          command: |
            npm run build
      - run:
          name: Modul - Tester
          command: |
            npm run test
      - restore_cache:
          name: Eksempel - Restore cache
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Eksempel - Installer npm pakker
          command: |
            cd example && npm ci
      - save_cache:
          name: Eksempel - Save cache
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Eksempel - Bygg React app
          command: |
            cd example && npm run build
      - run:
          name: Eksempel - Tester
          command: |
            cd example && npm run test
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
            - example/build/*

  deploy-til-dev:
    docker:
      - image: circleci/node:11.7.0

    steps:
      - checkout
      - setup_remote_docker
      - sett-miljovariabler
      - attach_workspace:
          at: .
      - run:
          name: Bygger Docker image
          command: docker build -t "$DOCKER_IMAGE_VERSIONED" -t "$DOCKER_IMAGE_UNVERSIONED" .
      - run:
          name: Pusher Docker image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push "$DOCKER_IMAGE_VERSIONED"
            docker push "$DOCKER_IMAGE_UNVERSIONED"
      - run:
          name: Deployer til dev
          command: |
            curl -i \
                -X POST \
                -d '{
                     "ref": "'"$COMMIT_SHORT"'",
                     "description": "Automated deployment request for arbeidsforhold from team personbruker",
                     "environment": "dev-sbs",
                     "required_contexts": [],
                     "payload": {
                       "version": [1, 0, 0],
                       "team": "personbruker",
                       "kubernetes": {
                         "resources": ['"$(cat nais-dev.json | jq '.spec.image = "'$DOCKER_IMAGE_VERSIONED'"')"']
                       }
                     }
                   }' \
                -H "Accept: application/vnd.github.ant-man-preview+json" \
                -u "$GH_USER":"$GH_TK" \
                https://api.github.com/repos/navikt/arbeidsforhold/deployments

  deploy-til-npm:
    docker:
      - image: circleci/node:11.7.0

    steps:
      - checkout
      - run:
          name: Versjon ${CIRCLE_TAG}
          command: echo "Lanser versjon ${CIRCLE_TAG} til npmjs"
      - run:
          name: Endrer versjon i package.json
          command: cat package.json | jq '.version = "${CIRCLE_TAG}"'
      - run:
          name: Autentiser med register
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Installererer avhengigheter
          command: |
            npm install
      - run:
          name: Publiser pakke
          command: |
            npm publish

commands:
  sett-miljovariabler:
    steps:
      - run:
          name: Setter miljøvariable
          command: |
            echo 'export COMMIT_SHORT="$(git rev-parse --short HEAD)"' >> $BASH_ENV
            echo 'export RELEASE_VERSION="$(git rev-list --count $CIRCLE_SHA1)"' >> $BASH_ENV
            echo 'export BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"' >> $BASH_ENV
            echo 'export BRANCH_PREFIX=`[ $BRANCH_NAME == "master" ] && echo "" || echo $BRANCH_NAME\_`' >> $BASH_ENV
            echo 'export DOCKER_IMAGE_VERSIONED="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$BRANCH_PREFIX$RELEASE_VERSION"' >> $BASH_ENV
            echo 'export DOCKER_IMAGE_UNVERSIONED="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV

workflows:
  bygg-og-deploy:
    jobs:
      - build-react-app:
          filters:
            tags:
              only: /.*/
      - bekreft-deploy-til-dev:
          type: approval
          requires:
            - build-react-app
          filters:
            branches:
              ignore: master
      - deploy-til-dev:
          name: manuell-deploy-til-dev
          requires:
            - bekreft-deploy-til-dev
      - deploy-til-dev:
          name: automatisk-deploy-til-dev
          requires:
            - build-react-app
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
      - deploy-til-npm:
          requires:
            - automatisk-deploy-til-dev
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
