name: Publish beta
on:
  workflow_dispatch

jobs:
  publish-beta:
    name: Publish to package registry
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      - name: Bump version
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          npm version prerelease --preid beta
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Publish package
        id: publish
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push new version tag
        if: steps.publish.outcome == 'success'
        run: git push
